test code detect

diff --git a/.github/workflows/pull-request-checker.yml b/.github/workflows/pull-request-checker.yml
--- a/.github/workflows/pull-request-checker.yml
+++ b/.github/workflows/pull-request-checker.yml
@@ -34,7 +34,7 @@ jobs:
       - name: Execute code detector
         run: |
           chmod +x $(which reek)
-          reek || (echo "Reek failed with warnings/errors" && exit 1)
+          reek features/ || (echo "Reek failed with warnings/errors" && exit 1)
 
       - name: Execute code static analyzer
         run: |
