retry

diff --git a/.github/workflows/pull-request-checker.yml b/.github/workflows/pull-request-checker.yml
--- a/.github/workflows/pull-request-checker.yml
+++ b/.github/workflows/pull-request-checker.yml
@@ -31,9 +31,10 @@ jobs:
       - name: Bundle Install
         run: bundle install
 
+      - name: Execute code detector
+        run: |
+          reek || (echo "Reek failed with warnings/errors" && exit 1)
+
       - name: Execute code static analyzer
         run: |
-          rubocop --fail-level warning || (echo "Rubocop failed with warnings or errors" && exit 1)
-
-      - name: Execute code detector
-        run: reek
+          rubocop --fail-level warning || (echo "Rubocop failed with warnings/errors" && exit 1)
