remove reek and make it bundled

diff --git a/.github/workflows/rubocop-checker.yml b/.github/workflows/rubocop-checker.yml
--- a/.github/workflows/rubocop-checker.yml
+++ b/.github/workflows/rubocop-checker.yml
@@ -1,4 +1,4 @@
-name: Rubocop Checker
+name: Pull Request Checker
 
 on:
   pull_request:
@@ -6,8 +6,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  rubocop-checker:
-    name: Execute Rubocop Checker
+  pipeline-checker:
+    name: Checker
     runs-on: ubuntu-latest
 
     steps:
@@ -18,19 +18,20 @@ jobs:
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.7.8
+
       - name: Config Gemfile for checker
         run: |
           mv Gemfile Gemfilee
           mv GemfileForChecker Gemfile
+
       - name: Install Bundler
         run: |
           gem install bundler -v '2.4.22'
+
       - name: Bundle Install
         run: bundle install
-      # Code static analyzer & formatter
-      - name: Execute Rubocop
+
+      - name: Execute code analyzer & detector
         run: |
-          rubocop --fail-level warning || exit 1
-      # Code detector
-      - name: Execute Reek
-        run: bundle exec reek
+          rubocop --fail-level warning || (echo "Rubocop failed with warnings or errors" && exit 1)
+          reek
